//
//Copyright 2022 Nokia.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/executor/executorpb/executor.proto

package executorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteFunctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Serialized resourceContext
	ResourceContext []byte `protobuf:"bytes,1,opt,name=resourceContext,proto3" json:"resourceContext,omitempty"`
	// the image associated with the execution request
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ExecuteFunctionRequest) Reset() {
	*x = ExecuteFunctionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_executor_executorpb_executor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionRequest) ProtoMessage() {}

func (x *ExecuteFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_executor_executorpb_executor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_executor_executorpb_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteFunctionRequest) GetResourceContext() []byte {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

func (x *ExecuteFunctionRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type ExecuteFunctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Serialized resourceContext, including structured function results
	ResourceContext []byte `protobuf:"bytes,1,opt,name=resourceContext,proto3" json:"resourceContext,omitempty"`
	// Additional log produced by the fucntion if any
	Log []byte `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *ExecuteFunctionResponse) Reset() {
	*x = ExecuteFunctionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_executor_executorpb_executor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionResponse) ProtoMessage() {}

func (x *ExecuteFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_executor_executorpb_executor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_executor_executorpb_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteFunctionResponse) GetResourceContext() []byte {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

func (x *ExecuteFunctionResponse) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_pkg_executor_executorpb_executor_proto protoreflect.FileDescriptor

var file_pkg_executor_executorpb_executor_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x22, 0x58, 0x0a, 0x16, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x17,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6c, 0x6f, 0x67, 0x32, 0x6c, 0x0a, 0x10, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x58, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x6e, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x66, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2f, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_executor_executorpb_executor_proto_rawDescOnce sync.Once
	file_pkg_executor_executorpb_executor_proto_rawDescData = file_pkg_executor_executorpb_executor_proto_rawDesc
)

func file_pkg_executor_executorpb_executor_proto_rawDescGZIP() []byte {
	file_pkg_executor_executorpb_executor_proto_rawDescOnce.Do(func() {
		file_pkg_executor_executorpb_executor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_executor_executorpb_executor_proto_rawDescData)
	})
	return file_pkg_executor_executorpb_executor_proto_rawDescData
}

var file_pkg_executor_executorpb_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_executor_executorpb_executor_proto_goTypes = []interface{}{
	(*ExecuteFunctionRequest)(nil),  // 0: executor.ExecuteFunctionRequest
	(*ExecuteFunctionResponse)(nil), // 1: executor.ExecuteFunctionResponse
}
var file_pkg_executor_executorpb_executor_proto_depIdxs = []int32{
	0, // 0: executor.FunctionExecutor.ExecuteFunction:input_type -> executor.ExecuteFunctionRequest
	1, // 1: executor.FunctionExecutor.ExecuteFunction:output_type -> executor.ExecuteFunctionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_executor_executorpb_executor_proto_init() }
func file_pkg_executor_executorpb_executor_proto_init() {
	if File_pkg_executor_executorpb_executor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_executor_executorpb_executor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_executor_executorpb_executor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_executor_executorpb_executor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_executor_executorpb_executor_proto_goTypes,
		DependencyIndexes: file_pkg_executor_executorpb_executor_proto_depIdxs,
		MessageInfos:      file_pkg_executor_executorpb_executor_proto_msgTypes,
	}.Build()
	File_pkg_executor_executorpb_executor_proto = out.File
	file_pkg_executor_executorpb_executor_proto_rawDesc = nil
	file_pkg_executor_executorpb_executor_proto_goTypes = nil
	file_pkg_executor_executorpb_executor_proto_depIdxs = nil
}
